server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/music?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # 配置时区
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    # 设置上传文件的大小
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)

# 加密算法配置      默认使用的加密算法是 PBEWithMD%AndDES
jasypt:
  encryptor:
    password: azfa23!-d  # 加密密钥
